# 使用 Compose 文件格式的第三版
version: '3'

# 定义两个服务：web 和 redis
services:
  # web 服务是 Django 项目
  web:
    # 使用当前目录下的 Dockerfile 构建镜像
    build: .
    # 将容器的 8000 端口映射到主机的 8000 端口
    ports:
      - "8000:8000"
    # 指定 web 服务依赖于 redis 服务，确保 redis 服务先启动
    depends_on:
      - redis

  # redis 服务是 Redis 数据库
  redis:
    # 使用官方的 Redis 镜像
    image: "redis:alpine"
    # 将容器的 6379 端口映射到主机的 6379 端口
    ports:
      - "6379:6379"
    # 设置映射，给Django连接
    container_name: redis